# Apps
'App: Dashboard':
  - apps/picsa-apps/dashboard/**/*
'App: Server':
  - apps/picsa-apps/server/**/*

# Tools
'Tool: Budget':
  - apps/picsa-tools/budget-tool/**/*
'Tool: Climate':
  - apps/picsa-tools/climate-tool/**/*
'Tool: Crop Probability':
  - apps/picsa-tools/crop-probability-tool/**/*
'Tool: Farmer Activity':
  - apps/picsa-tools/farmer-activity/**/*
'Tool: Manual':
  - apps/picsa-tools/manual-tool/**/*
'Tool: Monitoring':
  - apps/picsa-tools/monitoring-tool/**/*
'Tool: Option':
  - apps/picsa-tools/option-tool/**/*
'Tool: Resources':
  - apps/picsa-tools/resources-tool/**/*
'Tool: Seasonal Calendar':
  - apps/picsa-tools/seasonal-calendar-tool/**/*
