# Apps
'App: Dashboard':
  - changed-files:
      - any-glob-to-any-file: 'apps/picsa-apps/dashboard/**/*'
'App: Server':
  - changed-files:
      - any-glob-to-any-file: 'apps/picsa-apps/server/**/*'

# Tools
'Tool: Budget':
  - changed-files:
      - any-glob-to-any-file: 'apps/picsa-tools/budget-tool/**/*'
'Tool: Climate':
  - changed-files:
      - any-glob-to-any-file: 'apps/picsa-tools/climate-tool/**/*'
'Tool: Crop Probability':
  - changed-files:
      - any-glob-to-any-file: 'apps/picsa-tools/crop-probability-tool/**/*'
'Tool: Farmer Activity':
  - changed-files:
      - any-glob-to-any-file: 'apps/picsa-tools/farmer-activity/**/*'
'Tool: Manual':
  - changed-files:
      - any-glob-to-any-file: 'apps/picsa-tools/manual-tool/**/*'
'Tool: Monitoring':
  - changed-files:
      - any-glob-to-any-file: 'apps/picsa-tools/monitoring-tool/**/*'
'Tool: Option':
  - changed-files:
      - any-glob-to-any-file: 'apps/picsa-tools/option-tool/**/*'
'Tool: Resources':
  - changed-files:
      - any-glob-to-any-file: 'apps/picsa-tools/resources-tool/**/*'
'Tool: Seasonal Calendar':
  - changed-files:
      - any-glob-to-any-file: 'apps/picsa-tools/seasonal-calendar-tool/**/*'
