# Apps
'App: Dashboard':
  - changed-files:
      - any-glob-to-any-file: 'apps/picsa-apps/dashboard/**/*'
# HACK - for now farmer pages are contained within extension app, to refactor in future
'App: Farmer':
  - changed-files:
      - any-glob-to-any-file: 'apps/picsa-tools/farmer-content/**/*'
'App: Extension':
  - changed-files:
      - any-glob-to-any-file: 'apps/picsa-tools/extension-content/**/*'
      - any-glob-to-any-file: 'apps/picsa-apps/app/**/*'
      - any-glob-to-any-file: 'apps/picsa-apps/app-native/**/*'

'CI / Automation':
  - changed-files:
      - any-glob-to-any-file: '.github/**/*'
      - any-glob-to-any-file: 'tools/workflows/**/*'

# Server
'Server: DB Migration':
  - changed-files:
      - any-glob-to-any-file: 'apps/picsa-server/supabase/migrations/**/*'
'Server: Functions':
  - changed-files:
      - any-glob-to-any-file: 'apps/picsa-server/supabase/functions/**/*'

# Tools
'Tool: Budget':
  - changed-files:
      - any-glob-to-any-file: 'apps/picsa-tools/budget-tool/**/*'
'Tool: Climate':
  - changed-files:
      - any-glob-to-any-file: 'apps/picsa-tools/climate-tool/**/*'
'Tool: Crop Probability':
  - changed-files:
      - any-glob-to-any-file: 'apps/picsa-tools/crop-probability-tool/**/*'
'Tool: Forecasts':
  - changed-files:
      - any-glob-to-any-file: 'apps/picsa-tools/forecasts-tool/**/*'
'Tool: Manual':
  - changed-files:
      - any-glob-to-any-file: 'apps/picsa-tools/manual-tool/**/*'
'Tool: Option':
  - changed-files:
      - any-glob-to-any-file: 'apps/picsa-tools/option-tool/**/*'
'Tool: Resources':
  - changed-files:
      - any-glob-to-any-file: 'apps/picsa-tools/resources-tool/**/*'
'Tool: Seasonal Calendar':
  - changed-files:
      - any-glob-to-any-file: 'apps/picsa-tools/seasonal-calendar-tool/**/*'
