# PR-Agent Configuration
# Documentation: https://docs.pr-agent.ai/

# https://docs.pr-agent.ai/installation/github/?h=fallback_models#using-configuration-files

# https://docs.pr-agent.ai/tools/describe/#configuration-options

[config]
model = "gemini/gemini-3.5-flash"
fallback_models = ["gemini/gemini-3.1-pro"]

[pr_description]
publish_description_as_comment = false
keep_original_user_description = true
use_description_markers = true
inline_code_comments = true

# Review Tool Customization (/review)
[pr_reviewer]
enable_inline_comments = true
num_code_suggestions = 4

# Code Improvement Tool Customization (/improve)
[pr_code_suggestions]
num_code_suggestions = 4
