checksumBehavior: update

compressionLevel: 0

enableGlobalCache: true

logFilters:
  - code: YN0060
    level: discard
  - code: YN0002
    level: discard

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.12.0.cjs
