checksumBehavior: update

compressionLevel: 0

enableGlobalCache: true

# Ensure packages are at least 7 days old to avoid 0-day exploits
# (except for trusted sources that may be updated more frequently)
npmMinimalAgeGate: 10080
npmPreapprovedPackages:
  - "@picsa/*"
  - "@angular/*"
  - "@capacitor/*"
  - "@nx/*"
  - "typescript"

logFilters:
  - code: YN0060
    level: discard
  - code: YN0002
    level: discard

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.12.0.cjs
