# sonar-project.properties
sonar.projectKey=e-picsa_picsa-apps
sonar.organization=e-picsa

# Rules used
sonar.issue.ignore.multicriteria=ignoreTSS2933

# typescript:S2933 - ignore rule to force `readonly` on all injected services
sonar.issue.ignore.multicriteria.ignoreTSS2933.ruleKey=typescript:S2933
sonar.issue.ignore.multicriteria.ignoreTSS2933.resourceKey=**/*