create table
  public.translations (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    en text null,
    mw_ny text null,
    sw text null,
    tg text null,
    zm_ny text null,
    constraint translations_pkey primary key (id)
  ) tablespace pg_default;