create table
  public.crop_data (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    variety text null,
    days text null,
    water _upper double precision null,
    water _lower double precision null,
    length_lower double precision null,
    length_upper double precision null,
    station_data bigint null,
    constraint crop_data_pkey primary key (id),
    constraint crop_data_station_data_fkey foreign key (station_data) references station_data (id)
  ) tablespace pg_default;