create table
  public.monitoring_forms (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    tittle text not null,
    description character varying null,
    "enketoDefinition" jsonb null,
    "summaryFields" jsonb[] null,
    "appCountries" text[] null,
    "enketoForm" text null,
    "enketoModel" text null,
    cover jsonb null,
    constraint monitoring_forms_pkey primary key (id)
  ) tablespace pg_default;