create table
  public.station_crop_information (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    station_name text null,
    water_lower double precision null,
    water_upper double precision null,
    length_lower double precision null,
    length_upper double precision null,
    station_notes text[] null,
    constraint station_crop_information_pkey primary key (id)
  ) tablespace pg_default;