create table
  public.monitoring_forms (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    title text not null,
    description character varying null,
    enketo_definition jsonb null,
    summary_fields jsonb[] null,
    app_countries text[] null,
    enketo_form text null,
    enketo_model text null,
    cover jsonb null,
    constraint monitoring_forms_pkey primary key (id)
  ) tablespace pg_default;