-- Backfill Zimbabwe downscaled crop water requirements and missing crop_data master rows.
-- Districts: Mangwe, Mwenezi, Chipinge, Rushinga. Masvingo already exists and is left as-is.
--
-- Part 1 inserts missing zw crop_data master rows: the dashboard probability table
-- (generateTable) drops any crop/variety with no matching crop_data row, which is why
-- only varieties already present (e.g. NATAL-COMMON, CBC-2, IT-18) rendered.
-- Days come from the extractor modal ranges (Rushinga direct from doc table);
-- maturity_period follows existing per-crop bands; additional_info is source district.
--
-- Part 2 upserts the downscaled water requirements. Crop keys are normalised to the
-- master taxonomy (pearl-millet/finger-millet -> millet, sugar-beans -> beans,
-- ground-nuts -> groundnuts, p/millet -> millet). Station links:
--   Mangwe -> Plumtree (zw/plumtree_met), Mwenezi -> Buffalo Range (zw/buffalo_range_met),
--   Chipinge -> Chisumbanje (zw/chisumbanje_met), Rushinga -> Mount Darwin (zw/mt_darwin,
--   doc notes Mt Darwin data is wetter than most of Rushinga).
-- Upserts on generated ids, safe to re-run.

insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'bambaranuts', 'MISODZI', 'medium', 90, 100, 'Mwenezi') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'bambaranuts', 'NYIMO-TSVUKU', 'medium', 90, 100, 'Mwenezi') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'beans', 'NUA-45', 'early', 85, 90, 'Mangwe') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'beans', 'SC-BOUNTY', 'early', 90, 90, 'Chipinge') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'cotton', 'BC-853', 'late', 120, 140, 'Rushinga') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'cotton', 'FQ-902', 'late', 120, 140, 'Rushinga') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'cotton', 'JAGUAR', 'late', 90, 105, 'Mwenezi') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'cotton', 'MAHYCO', 'late', 90, 105, 'Mwenezi') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'cotton', 'QM-301', 'late', 120, 120, 'Mangwe') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'cotton', 'QM-302', 'late', 150, 150, 'Mwenezi') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'cotton', 'SZ-9314', 'late', 120, 140, 'Rushinga') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'cowpeas', 'BLACK-EYED-BEAN', 'early', 80, 100, 'Rushinga') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'cowpeas', 'CBC-1', 'early', 75, 80, 'Chipinge') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'cowpeas', 'CBC-3', 'early', 65, 65, 'Mangwe') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'cowpeas', 'CBC-4', 'early', 80, 100, 'Rushinga') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'cowpeas', 'NYEMBA-YOKUTANDA', 'early', 90, 90, 'Mwenezi') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'groundnuts', 'MWENJE', 'medium', 130, 130, 'Chipinge') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'groundnuts', 'NYANDA', 'medium', 130, 130, 'Mwenezi') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'groundnuts', 'RED-MAKHULU', 'medium', 110, 110, 'Mangwe') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'groundnuts', 'TUMBE', 'medium', 110, 130, 'Rushinga') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'maize', 'K-2', 'early', 70, 90, 'Mangwe') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'maize', 'M-301', 'early', 80, 80, 'Chipinge') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'maize', 'MRI-514', 'early', 120, 120, 'Chipinge') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'maize', 'MRI-624', 'medium', 140, 140, 'Chipinge') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'maize', 'PG-551', 'early', 90, 120, 'Rushinga') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'maize', 'PG-553', 'early', 90, 120, 'Rushinga') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'maize', 'PG-561', 'early', 90, 120, 'Rushinga') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'maize', 'RED-COB', 'early', 90, 100, 'Mwenezi') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'maize', 'SC-301', 'early', 110, 110, 'Mangwe') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'maize', 'SC-401', 'early', 90, 90, 'Mwenezi') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'maize', 'SC-403', 'early', 90, 90, 'Mangwe') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'maize', 'SC-417', 'early', 110, 110, 'Chipinge') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'maize', 'SC-500', 'early', 90, 120, 'Rushinga') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'maize', 'SC-513', 'early', 120, 120, 'Mwenezi') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'maize', 'SC-529', 'early', 130, 130, 'Chipinge') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'maize', 'SC-533', 'early', 130, 130, 'Chipinge') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'maize', 'SC-537', 'early', 130, 130, 'Chipinge') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'maize', 'SC-627', 'medium', 140, 140, 'Chipinge') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'maize', 'SC-649', 'medium', 140, 140, 'Chipinge') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'maize', 'SY-5499', 'early', 130, 130, 'Chipinge') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'maize', 'ZAP-41', 'early', 90, 110, 'Rushinga') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'maize', 'ZAP-53', 'early', 90, 120, 'Rushinga') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'maize', 'ZAP-55', 'early', 90, 120, 'Rushinga') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'maize', 'ZS-265', 'medium', 150, 150, 'Chipinge') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'millet', 'MUNGOZA', 'medium', 140, 140, 'Chipinge') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'millet', 'MUSWEWESHOKO', 'medium', 90, 90, 'Mwenezi') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'millet', 'OKASHANA', 'medium', 90, 90, 'Chipinge') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'millet', 'OKASHANA-1', 'medium', 75, 75, 'Mwenezi') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'millet', 'OPVS', 'medium', 120, 130, 'Mangwe') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'millet', 'PMV-3', 'medium', 75, 75, 'Mwenezi') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'roundnuts', 'MANA', 'late', 140, 150, 'Mangwe') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'roundnuts', 'ROUNDNUTS', 'late', 110, 110, 'Chipinge') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'roundnuts', 'ZUMA', 'late', 140, 150, 'Mangwe') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'sesame', 'SESAMME', 'early', 120, 120, 'Chipinge') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'sorghum', 'HWEDZA', 'medium', 90, 90, 'Mwenezi') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'sorghum', 'MACIA', 'medium', 110, 110, 'Mwenezi') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'sorghum', 'MANDENDE', 'medium', 120, 120, 'Mwenezi') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'sorghum', 'OPVS', 'medium', 90, 90, 'Mangwe') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'sorghum', 'RAKODZI', 'medium', 110, 110, 'Chipinge') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'sorghum', 'SC-SMILE', 'medium', 105, 105, 'Chipinge') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'sorghum', 'SILA', 'medium', 90, 90, 'Mwenezi') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'sorghum', 'SV-4', 'medium', 120, 120, 'Chipinge') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'sorghum', 'VUMBA-GEKWE', 'medium', 80, 100, 'Rushinga') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'sunflower', 'HYBRID', 'medium', 120, 120, 'Mangwe') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'sunflower', 'PAN-7170', 'medium', 90, 110, 'Rushinga') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'sunflower', 'PAN-7180', 'medium', 90, 110, 'Rushinga') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'sweet-potatoes', 'BRONDALE', 'late', 120, 120, 'Chipinge') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'sweet-potatoes', 'CHIBHUTATA', 'late', 120, 120, 'Chipinge') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'sweet-potatoes', 'CHINGOVHA', 'late', 120, 120, 'Chipinge') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'sweet-potatoes', 'GERMANY2', 'late', 120, 120, 'Chipinge') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();
insert into public.crop_data (country_code, crop, variety, maturity_period, days_lower, days_upper, additional_info) values ('zw', 'sweet-potatoes', 'KORI', 'late', 120, 120, 'Chipinge') on conflict (country_code, crop, variety) do update set days_lower = excluded.days_lower, days_upper = excluded.days_upper, maturity_period = excluded.maturity_period, updated_at = now();

-- Ensure referenced climate stations exist before inserting downscaled rows
-- (guarantees foreign key constraint succeeds during clean local resets without altering remote data)
insert into public.climate_stations (country_code, station_id, station_name, district)
values
  ('zw', 'plumtree_met', 'PLUMTREE (MET)', 'Matabeleland South'),
  ('zw', 'buffalo_range_met', 'BUFFALO RANGE (MET)', 'Masvingo'),
  ('zw', 'chisumbanje_met', 'CHISUMBANJE (MET)', 'Manicaland'),
  ('zw', 'mt_darwin', 'Mt Darwin', 'Mashonaland Central')
on conflict (country_code, station_id) do nothing;

insert into public.crop_data_downscaled (country_code, location_id, water_requirements, station_id) values ('zw', 'mangwe', '{"maize":{"SC-301":300,"SC-403":300,"K-2":300},"sorghum":{"OPVS":300},"millet":{"OPVS":400},"cowpeas":{"CBC-2":250,"IT-18":250,"CBC-3":250},"groundnuts":{"NATAL-COMMON":350,"RED-MAKHULU":350},"roundnuts":{"MANA":450,"ZUMA":450},"sunflower":{"HYBRID":400},"cotton":{"QM-301":450},"beans":{"NUA-45":350}}', 'zw/plumtree_met') on conflict (id) do update set water_requirements = excluded.water_requirements, station_id = excluded.station_id, updated_at = now();
insert into public.crop_data_downscaled (country_code, location_id, water_requirements, station_id) values ('zw', 'mwenezi', '{"sorghum":{"MACIA":250,"SILA":350,"HWEDZA":350,"MANDENDE":500},"millet":{"OKASHANA-1":350,"PMV-3":350,"MUSWEWESHOKO":350},"maize":{"SC-401":400,"SC-403":400,"PAN-413":400,"SC-513":550,"RED-COB":400},"groundnuts":{"NYANDA":270,"NATAL-COMMON":400},"bambaranuts":{"MISODZI":400,"NYIMO-TSVUKU":400},"cowpeas":{"CBC-2":300,"NYEMBA-YOKUTANDA":400},"cotton":{"QM-301":700,"QM-302":600,"MAHYCO":350,"JAGUAR":350}}', 'zw/buffalo_range_met') on conflict (id) do update set water_requirements = excluded.water_requirements, station_id = excluded.station_id, updated_at = now();
insert into public.crop_data_downscaled (country_code, location_id, water_requirements, station_id) values ('zw', 'chipinge', '{"maize":{"SC-403":400,"SC-301":400,"SC-417":400,"SC-419":400,"SC-533":450,"SC-529":450,"SC-537":450,"SC-627":700,"MRI-514":450,"MRI-624":600,"SC-649":700,"ZS-265":600,"M-301":400,"PGS-65":600,"SY-5499":500,"PAN-413":400},"sorghum":{"MACIA":400,"SV-2":450,"SV-4":450,"SC-SILA":450,"SC-SMILE":450,"RAKODZI":450},"millet":{"PMV-1":400,"PMV-2":400,"OKASHANA":400,"MUNGOZA":600},"beans":{"SC-BOUNTY":400,"SC-SHARP":400},"sweet-potatoes":{"CHINGOVHA":600,"GERMANY2":600,"KORI":600,"BRONDALE":600,"CHIBHUTATA":600},"groundnuts":{"NYANDA":450,"MWENJE":450,"NATAL-COMMON":450},"sesame":{"SESAMME":400},"roundnuts":{"ROUNDNUTS":450},"cowpeas":{"CBC-2":350,"CBC-1":350,"IT-18":350}}', 'zw/chisumbanje_met') on conflict (id) do update set water_requirements = excluded.water_requirements, station_id = excluded.station_id, updated_at = now();
insert into public.crop_data_downscaled (country_code, location_id, water_requirements, station_id) values ('zw', 'rushinga', '{"maize":{"SC-403":300,"SC-417":300,"SC-419":300,"PAN-413":300,"ZAP-41":300,"SC-500":350,"PG-551":350,"PG-553":350,"PG-561":350,"ZAP-53":350,"ZAP-55":350},"sorghum":{"MACIA":250,"SC-SMILE":250,"VUMBA-GEKWE":250,"SV-3":250,"SV-4":250},"cotton":{"SZ-9314":450,"BC-853":450,"FQ-902":450},"groundnuts":{"NATAL-COMMON":400,"VALENCIA":400,"TUMBE":400},"cowpeas":{"CBC-2":250,"CBC-3":250,"CBC-4":250,"BLACK-EYED-BEAN":250},"millet":{"PMV-1":250,"PMV-2":250,"PMV-3":250,"OKASHANA":250},"sunflower":{"PAN-7170":300,"PAN-7180":300}}', 'zw/mt_darwin') on conflict (id) do update set water_requirements = excluded.water_requirements, station_id = excluded.station_id, updated_at = now();
