/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v2/status/': {
    /**
     * Get Status
     * @description Health check endpoint for v2.
     */
    get: operations['get_status_v2_status__get'];
  };
  '/v2/annual_rainfall_summaries/': {
    /**
     * Get Annual Rainfall Summaries
     * @description Retrieve annual rainfall summaries from PostgreSQL.
     */
    post: operations['get_annual_rainfall_summaries_v2_annual_rainfall_summaries__post'];
  };
  '/v2/annual_temperature_summaries/': {
    /**
     * Get Annual Temperature Summaries
     * @description Retrieve annual temperature summaries from PostgreSQL.
     */
    post: operations['get_annual_temperature_summaries_v2_annual_temperature_summaries__post'];
  };
  '/v2/crop_success_probabilities/': {
    /**
     * Get Crop Success Probabilities
     * @description Retrieve full crop success probabilities lookup table from PostgreSQL.
     */
    post: operations['get_crop_success_probabilities_v2_crop_success_probabilities__post'];
  };
  '/v2/monthly_temperature_summaries/': {
    /**
     * Get Monthly Temperature Summaries
     * @description Retrieve monthly temperature summaries from PostgreSQL.
     */
    post: operations['get_monthly_temperature_summaries_v2_monthly_temperature_summaries__post'];
  };
  '/v2/season_start_probabilities/': {
    /**
     * Get Season Start Probabilities
     * @description Retrieve cumulative season start probabilities from PostgreSQL.
     */
    post: operations['get_season_start_probabilities_v2_season_start_probabilities__post'];
  };
  '/v2/station/{country}': {
    /**
     * Read Stations
     * @description Retrieve all stations for a given country code.
     */
    get: operations['read_stations_v2_station__country__get'];
  };
  '/v2/station/{country}/{station_id}': {
    /**
     * Read Station Detail
     * @description Retrieve station metadata and climate definitions for a station.
     */
    get: operations['read_station_detail_v2_station__country___station_id__get'];
  };
  '/v2/select_query/': {
    /** Run Select Query */
    post: operations['run_select_query_v2_select_query__post'];
  };
  '/v2/documents/{country}': {
    /** Get Documents */
    get: operations['get_documents_v2_documents__country__get'];
  };
  '/v2/documents/{country}/{filepath}': {
    /**
     * Download Document
     * @description Download a specific document
     */
    get: operations['download_document_v2_documents__country___filepath__get'];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** AnnualRain */
    AnnualRain: {
      /** Annual Rain */
      annual_rain?: boolean;
      /** N Rain */
      n_rain?: boolean;
      /** Rain Day */
      rain_day?: number;
      /** Na Rm */
      na_rm?: boolean;
      /** Na N */
      na_n?: number;
      /** Na N Non */
      na_n_non?: number;
      /** Na Consec */
      na_consec?: number;
      /** Na Prop */
      na_prop?: number;
      /** S Start Doy */
      s_start_doy?: number;
    };
    /** AnnualRainfallSummariesMetadata */
    AnnualRainfallSummariesMetadata: {
      annual_rain?: components['schemas']['AnnualRain'];
      start_rains?: components['schemas']['StartRains'];
      end_rains?: components['schemas']['EndRains'];
      end_season?: components['schemas']['EndSeason'];
      seasonal_rain?: components['schemas']['SeasonalRain'];
      seasonal_length?: components['schemas']['SeasonalLength'];
    };
    /** AnnualRainfallSummariesParameters */
    AnnualRainfallSummariesParameters: {
      /**
       * Country
       * @default mw_test
       * @enum {string}
       */
      country?:
        | 'zm'
        | 'mw'
        | 'zw'
        | 'zm_test'
        | 'mw_test'
        | 'zw_test'
        | 'zm_workshops'
        | 'mw_workshops'
        | 'zw_workshops'
        | 'internal_tests';
      /**
       * Station Id
       * @default Kasungu
       */
      station_id?: string;
      /**
       * Summaries
       * @default [
       *   "annual_rain",
       *   "start_rains",
       *   "end_rains",
       *   "end_season",
       *   "seasonal_rain",
       *   "seasonal_length"
       * ]
       */
      summaries?: ('annual_rain' | 'start_rains' | 'end_rains' | 'end_season' | 'seasonal_rain' | 'seasonal_length')[];
      /**
       * Override
       * @default false
       */
      override?: boolean;
    };
    /** AnnualRainfallSummariesResponce */
    AnnualRainfallSummariesResponce: {
      /** Generation Id */
      generation_id?: string;
      /**
       * Generation Timestamp
       * Format: date-time
       */
      generation_timestamp?: string;
      metadata: components['schemas']['AnnualRainfallSummariesMetadata'];
      /** Data */
      data: components['schemas']['AnnualRainfallSummariesdata'][];
    };
    /** AnnualRainfallSummariesdata */
    AnnualRainfallSummariesdata: {
      /** Station */
      station: string;
      /** Year */
      year: number;
      /** Annual Rain */
      annual_rain?: number;
      /** N Rain */
      n_rain?: number;
      /** Start Rains Doy */
      start_rains_doy?: number;
      /** Start Rains Date */
      start_rains_date?: unknown;
      /** Start Rains Status */
      start_rains_status?: boolean;
      /** End Rains Doy */
      end_rains_doy?: number;
      /** End Rains Date */
      end_rains_date?: unknown;
      /** End Rains Status */
      end_rains_status?: boolean;
      /** Seasonal Rain */
      seasonal_rain?: number;
      /** N Seasonal Rain */
      n_seasonal_rain?: number;
      /** Season Length */
      season_length?: number;
      /** End Season Doy */
      end_season_doy?: number;
      /** End Season Date */
      end_season_date?: unknown;
      /** End Season Status */
      end_season_status?: boolean;
    };
    /** AnnualTempartureSummariesdata */
    AnnualTempartureSummariesdata: {
      /** Station */
      station: string;
      /** Year */
      year: number;
      /** Mean Tmin */
      mean_tmin?: number;
      /** Mean Tmax */
      mean_tmax?: number;
      /** Min Tmin */
      min_tmin?: number;
      /** Min Tmax */
      min_tmax?: number;
      /** Max Tmin */
      max_tmin?: number;
      /** Max Tmax */
      max_tmax?: number;
    };
    /** AnnualTemperatureSummariesParameters */
    AnnualTemperatureSummariesParameters: {
      /**
       * Country
       * @default mw_test
       * @enum {string}
       */
      country?:
        | 'zm'
        | 'mw'
        | 'zw'
        | 'zm_test'
        | 'mw_test'
        | 'zw_test'
        | 'zm_workshops'
        | 'mw_workshops'
        | 'zw_workshops'
        | 'internal_tests';
      /**
       * Station Id
       * @default Kasungu
       */
      station_id?: string;
      /**
       * Summaries
       * @default [
       *   "mean_tmin",
       *   "mean_tmax",
       *   "min_tmin",
       *   "min_tmax",
       *   "max_tmin",
       *   "max_tmax"
       * ]
       */
      summaries?: ('mean_tmin' | 'mean_tmax' | 'min_tmin' | 'min_tmax' | 'max_tmin' | 'max_tmax')[];
      /**
       * Override
       * @default false
       */
      override?: boolean;
    };
    /** AnnualTemperatureSummariesResponce */
    AnnualTemperatureSummariesResponce: {
      /** Generation Id */
      generation_id?: string;
      /**
       * Generation Timestamp
       * Format: date-time
       */
      generation_timestamp?: string;
      metadata: components['schemas']['TemperatureSummariesMetadata'];
      /** Data */
      data: components['schemas']['AnnualTempartureSummariesdata'][];
    };
    /** CropSuccessProbabilitiesMetadata */
    CropSuccessProbabilitiesMetadata: {
      start_rains?: components['schemas']['StartRains'];
      end_rains?: components['schemas']['EndRains'];
      crops_success?: components['schemas']['CropsSuccess'];
    };
    /** CropSuccessProbabilitiesParameters */
    CropSuccessProbabilitiesParameters: {
      /**
       * Country
       * @default mw_test
       * @enum {string}
       */
      country?:
        | 'zm'
        | 'mw'
        | 'zw'
        | 'zm_test'
        | 'mw_test'
        | 'zw_test'
        | 'zm_workshops'
        | 'mw_workshops'
        | 'zw_workshops'
        | 'internal_tests';
      /**
       * Station Id
       * @default Kasungu
       */
      station_id?: string;
    };
    /** CropSuccessProbabilitiesResponce */
    CropSuccessProbabilitiesResponce: {
      /** Generation Id */
      generation_id?: string;
      /**
       * Generation Timestamp
       * Format: date-time
       */
      generation_timestamp?: string;
      metadata: components['schemas']['CropSuccessProbabilitiesMetadata'];
      /** Data */
      data: components['schemas']['CropSuccessProbabilitiesdata'][];
    };
    /** CropSuccessProbabilitiesdata */
    CropSuccessProbabilitiesdata: {
      /** Station */
      station: string;
      /** Total Rain */
      total_rain: number;
      /** Plant Day */
      plant_day: number;
      /** Plant Length */
      plant_length: number;
      /** Prop Success With Start */
      prop_success_with_start: number;
      /** Prop Success No Start */
      prop_success_no_start: number;
    };
    /** CropsSuccess */
    CropsSuccess: {
      /** Water Requirements */
      water_requirements?:
        | string
        | {
            [key: string]: number;
          };
      /** Planting Dates */
      planting_dates?:
        | string
        | {
            [key: string]: number;
          };
      /** Planting Length */
      planting_length?:
        | string
        | {
            [key: string]: number;
          };
    };
    /** DocumentMetadata */
    DocumentMetadata: {
      /** Name */
      name: string;
      /** Contenttype */
      contentType: string;
      /** Size */
      size: number;
      /** Timecreated */
      timeCreated: string;
      /** Updated */
      updated: string;
      /** Metadata */
      metadata?: {
        [key: string]: string;
      };
    };
    /** EndRains */
    EndRains: {
      /** Start Day */
      start_day?: number;
      /** End Day */
      end_day?: number;
      /** Output */
      output?: string | string[];
      /** Min Rainfall */
      min_rainfall?: number;
      /** Interval Length */
      interval_length?: number;
      /** S Start Doy */
      s_start_doy?: number;
    };
    /** EndSeason */
    EndSeason: {
      /** Start Day */
      start_day?: number;
      /** End Day */
      end_day?: number;
      /** Water Balance Max */
      water_balance_max?: number;
      /** Capacity */
      capacity?: number;
      /** Evaporation */
      evaporation?: string;
      /** Evaporation Value */
      evaporation_value?: number;
      /** S Start Doy */
      s_start_doy?: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** MonthlyTempartureSummariesdata */
    MonthlyTempartureSummariesdata: {
      /** Station */
      station: string;
      /** Year */
      year: number;
      /** Mean Tmin */
      mean_tmin?: number;
      /** Mean Tmax */
      mean_tmax?: number;
      /** Min Tmin */
      min_tmin?: number;
      /** Min Tmax */
      min_tmax?: number;
      /** Max Tmin */
      max_tmin?: number;
      /** Max Tmax */
      max_tmax?: number;
      /** Month */
      month: number;
    };
    /** MonthlyTemperatureSummariesParameters */
    MonthlyTemperatureSummariesParameters: {
      /**
       * Country
       * @default mw_test
       * @enum {string}
       */
      country?:
        | 'zm'
        | 'mw'
        | 'zw'
        | 'zm_test'
        | 'mw_test'
        | 'zw_test'
        | 'zm_workshops'
        | 'mw_workshops'
        | 'zw_workshops'
        | 'internal_tests';
      /**
       * Station Id
       * @default Kasungu
       */
      station_id?: string;
      /**
       * Summaries
       * @default [
       *   "mean_tmin",
       *   "mean_tmax",
       *   "min_tmin",
       *   "min_tmax",
       *   "max_tmin",
       *   "max_tmax"
       * ]
       */
      summaries?: ('mean_tmin' | 'mean_tmax' | 'min_tmin' | 'min_tmax' | 'max_tmin' | 'max_tmax')[];
      /**
       * Override
       * @default false
       */
      override?: boolean;
    };
    /** MonthlyTemperatureSummariesResponce */
    MonthlyTemperatureSummariesResponce: {
      /** Generation Id */
      generation_id?: string;
      /**
       * Generation Timestamp
       * Format: date-time
       */
      generation_timestamp?: string;
      metadata: components['schemas']['TemperatureSummariesMetadata'];
      /** Data */
      data: components['schemas']['MonthlyTempartureSummariesdata'][];
    };
    /** SeasonStartProbabilities */
    SeasonStartProbabilities: {
      /** Specified Day */
      specified_day?:
        | number[]
        | {
            [key: string]: number;
          };
    };
    /** SeasonStartProbabilitiesMetadata */
    SeasonStartProbabilitiesMetadata: {
      start_rains?: components['schemas']['StartRains'];
      season_start_probabilities?: components['schemas']['SeasonStartProbabilities'];
    };
    /** SeasonStartProbabilitiesParameters */
    SeasonStartProbabilitiesParameters: {
      /**
       * Country
       * @default mw_test
       * @enum {string}
       */
      country?:
        | 'zm'
        | 'mw'
        | 'zw'
        | 'zm_test'
        | 'mw_test'
        | 'zw_test'
        | 'zm_workshops'
        | 'mw_workshops'
        | 'zw_workshops'
        | 'internal_tests';
      /**
       * Station Id
       * @default Kasungu
       */
      station_id?: string;
      /**
       * Start Dates
       * @default [
       *   200,
       *   220,
       *   250,
       *   270,
       *   300,
       *   320
       * ]
       */
      start_dates?: number[];
      /**
       * Override
       * @default false
       */
      override?: boolean;
    };
    /** SeasonStartProbabilitiesResponce */
    SeasonStartProbabilitiesResponce: {
      /** Generation Id */
      generation_id?: string;
      /**
       * Generation Timestamp
       * Format: date-time
       */
      generation_timestamp?: string;
      metadata: components['schemas']['SeasonStartProbabilitiesMetadata'];
      /** Data */
      data: components['schemas']['SeasonStartProbabilitiesdata'][];
    };
    /** SeasonStartProbabilitiesdata */
    SeasonStartProbabilitiesdata: {
      /** Station */
      station: string;
      /** Day */
      day: number;
      /** Proportion */
      proportion: number;
    };
    /** SeasonalLength */
    SeasonalLength: {
      /** End Type */
      end_type?: string;
    };
    /** SeasonalRain */
    SeasonalRain: {
      /** Total Rain */
      total_rain?: number | boolean;
      /** N Rain */
      n_rain?: boolean;
      /** Rain Day */
      rain_day?: number;
      /** Na Rm */
      na_rm?: boolean;
      /** Na N */
      na_n?: number;
      /** Na N Non */
      na_n_non?: number;
      /** Na Consec */
      na_consec?: number;
      /** Na Prop */
      na_prop?: number;
    };
    /** SeasonalTotalRainfall */
    SeasonalTotalRainfall: {
      /** Na Prop */
      na_prop?: number;
    };
    /** SelectQueryRequest */
    SelectQueryRequest: {
      /**
       * Table Name
       * @enum {string}
       */
      table_name: 'crop' | 'definition' | 'station' | 'summary' | 'summary_station_metadata';
      /**
       * Columns
       * @description Optional list of allowed columns. Empty means all allowed columns.
       */
      columns?: string[];
      /** Station Id */
      station_id: string;
      /**
       * Order By
       * @description Optional sort column. Must be allowed for the selected table.
       */
      order_by?: string;
      /**
       * Order Direction
       * @default desc
       * @enum {string}
       */
      order_direction?: 'asc' | 'desc';
      /**
       * Max Rows
       * @default 100
       */
      max_rows?: number;
      /**
       * Generation Id
       * @description Optional generation/definition identifier to filter by.
       */
      generation_id?: string;
    };
    /** SelectQueryResponse */
    SelectQueryResponse: {
      /** Columns */
      columns: string[];
      /** Row Count */
      row_count: number;
      /** Rows */
      rows: Record<string, never>[];
      /** Generation Id */
      generation_id?: string;
      /**
       * Generation Timestamp
       * Format: date-time
       */
      generation_timestamp?: string;
    };
    /** StartRains */
    StartRains: {
      /** Start Day */
      start_day?: number;
      /** End Day */
      end_day?: number;
      /** Threshold */
      threshold?: number;
      /** Total Rainfall */
      total_rainfall?: boolean;
      /** Over Days */
      over_days?: number;
      /** Amount Rain */
      amount_rain?: number;
      /** Proportion */
      proportion?: boolean;
      /** Prob Rain Day */
      prob_rain_day?: number;
      /** Dry Spell */
      dry_spell?: boolean;
      /** Spell Max Dry Days */
      spell_max_dry_days?: number;
      /** Spell Interval */
      spell_interval?: number;
      /** Dry Period */
      dry_period?: boolean;
      /** Max Rain */
      max_rain?: number;
      /** Period Interval */
      period_interval?: number;
      /** Period Max Dry Days */
      period_max_dry_days?: number;
      /** S Start Doy */
      s_start_doy?: number;
      /** Number Rain Days */
      number_rain_days?: boolean;
      /** Min Rain Days */
      min_rain_days?: number;
      /** Rain Day Interval */
      rain_day_interval?: number;
    };
    /** StationAndDefintionResponce */
    StationAndDefintionResponce: {
      /** Station Id */
      station_id: string;
      /** Station Name */
      station_name: string;
      /** Latitude */
      latitude?: number;
      /** Longitude */
      longitude?: number;
      /** Elevation */
      elevation?: number;
      /** District */
      district?: string;
      /**
       * Country Code
       * @enum {string}
       */
      country_code:
        | 'zm'
        | 'mw'
        | 'zw'
        | 'zm_test'
        | 'mw_test'
        | 'zw_test'
        | 'zm_workshops'
        | 'mw_workshops'
        | 'zw_workshops'
        | 'internal_tests';
      /**
       * Generation Timestamp
       * Format: date-time
       */
      generation_timestamp?: string;
      /** Generation Id */
      generation_id?: string;
      /** Definitions Id */
      definitions_id: unknown[];
      /** Climsoft List */
      climsoft_list?: string[];
      data: components['schemas']['StationDefinitionDataResponce'];
    };
    /** StationDataResponce */
    StationDataResponce: {
      /** Station Id */
      station_id: string;
      /** Station Name */
      station_name: string;
      /** Latitude */
      latitude?: number;
      /** Longitude */
      longitude?: number;
      /** Elevation */
      elevation?: number;
      /** District */
      district?: string;
      /**
       * Country Code
       * @enum {string}
       */
      country_code:
        | 'zm'
        | 'mw'
        | 'zw'
        | 'zm_test'
        | 'mw_test'
        | 'zw_test'
        | 'zm_workshops'
        | 'mw_workshops'
        | 'zw_workshops'
        | 'internal_tests';
      /**
       * Generation Timestamp
       * Format: date-time
       */
      generation_timestamp?: string;
    };
    /** StationDefinitionDataResponce */
    StationDefinitionDataResponce: {
      start_rains?: components['schemas']['StartRains'];
      end_rains?: components['schemas']['EndRains'];
      end_season?: components['schemas']['EndSeason'];
      seasonal_length?: components['schemas']['SeasonalLength'];
      annual_rain?: components['schemas']['AnnualRain'];
      seasonal_rain?: components['schemas']['SeasonalRain'];
      min_tmin?: components['schemas']['Temp'];
      max_tmin?: components['schemas']['Temp'];
      mean_tmin?: components['schemas']['Temp'];
      min_tmax?: components['schemas']['Temp'];
      max_tmax?: components['schemas']['Temp'];
      mean_tmax?: components['schemas']['Temp'];
      crops_success?: components['schemas']['CropsSuccess'];
      season_start_probabilities?: components['schemas']['SeasonStartProbabilities'];
      seasonal_total_rainfall?: components['schemas']['SeasonalTotalRainfall'];
    };
    /** StationListResponce */
    StationListResponce: {
      /** Data */
      data: components['schemas']['StationDataResponce'][];
    };
    /** Temp */
    Temp: {
      /** To */
      to?: string | string[];
      /** Na Rm */
      na_rm?: boolean;
      /** Na N */
      na_n?: number;
      /** Na N Non */
      na_n_non?: number;
      /** Na Consec */
      na_consec?: number;
      /** Na Prop */
      na_prop?: number;
      /** S Start Doy */
      s_start_doy?: number;
    };
    /** TemperatureSummariesMetadata */
    TemperatureSummariesMetadata: {
      mean_tmin?: components['schemas']['Temp'];
      mean_tmax?: components['schemas']['Temp'];
      min_tmin?: components['schemas']['Temp'];
      min_tmax?: components['schemas']['Temp'];
      max_tmin?: components['schemas']['Temp'];
      max_tmax?: components['schemas']['Temp'];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /**
     * CropRecord
     * @description Schema representing a record in the 'crop' table.
     * Contains agricultural crop success and rainfall metrics for a station and season.
     */
    CropRecord: {
      /**
       * Station Id
       * @description Station identifier
       */
      station_id?: string;
      /**
       * Year
       * @description Year or agricultural season identifier
       */
      year?: string;
      /**
       * Plant Day
       * @description Planting day of year (day number)
       */
      plant_day?: number;
      /**
       * Plant Length
       * @description Length of crop growing period in days
       */
      plant_length?: number;
      /**
       * Rain Total
       * @description Total rainfall during crop growing period (mm)
       */
      rain_total?: number;
      /**
       * Include Start Condition
       * @description Whether start-of-season conditions were applied
       */
      include_start_condition?: boolean;
      /**
       * Summary Type
       * @description Type of summary (e.g. crop_success)
       */
      summary_type?: string;
      /**
       * Summary Element
       * @description Climate element summarized
       */
      summary_element?: string;
      /**
       * Summary Value
       * @description Statistical summary result value
       */
      summary_value?: string;
      /**
       * Definition Id
       * @description Associated statistical definition ID
       */
      definition_id?: string;
      /**
       * Status
       * @description Record validation or processing status
       */
      status?: string;
      /**
       * Time Stamp
       * Format: date-time
       * @description Timestamp of record creation or last update
       */
      time_stamp?: string;
    };
    /**
     * DefinitionRecord
     * @description Schema representing a record in the 'definition' table.
     * Defines statistical criteria, parameters, and metadata for climate summaries.
     */
    DefinitionRecord: {
      /**
       * Definition Id
       * @description Unique definition identifier (NOT NULL in DB)
       */
      definition_id?: string;
      /**
       * Time Stamp
       * Format: date-time
       * @description Timestamp of definition creation/update (NOT NULL in DB)
       */
      time_stamp?: string;
      /**
       * Summary Element
       * @description Summarized element (e.g. rainfall, temperature)
       */
      summary_element?: string;
      /**
       * Summary Type
       * @description Type of statistical summary
       */
      summary_type?: string;
      /**
       * Definition Value
       * @description JSON object containing definition parameters and thresholds
       */
      definition_value?: Record<string, never>;
      /**
       * Accreditation
       * @description Authoritative source or accreditation body
       */
      accreditation?: string;
    };
    /**
     * StationRecord
     * @description Schema representing a record in the 'station' table.
     * Contains geospatial metadata and status for meteorological stations.
     */
    StationRecord: {
      /**
       * Station Id
       * @description Unique meteorological station identifier (NOT NULL in DB)
       */
      station_id?: string;
      /**
       * Station Name
       * @description Human-readable station name
       */
      station_name?: string;
      /**
       * Latitude
       * @description Geographic latitude in decimal degrees
       */
      latitude?: number;
      /**
       * Longitude
       * @description Geographic longitude in decimal degrees
       */
      longitude?: number;
      /**
       * Elevation
       * @description Station elevation above sea level in meters
       */
      elevation?: number;
      /**
       * District
       * @description Administrative district name
       */
      district?: string;
      /**
       * Country Code
       * @description Country code (e.g. zm, mw, zw)
       */
      country_code?: string;
      /**
       * Time Stamp
       * Format: date-time
       * @description Timestamp of record creation or update
       */
      time_stamp?: string;
      /**
       * Status
       * @description Operational status of the station
       */
      status?: string;
    };
    /**
     * SummaryRecord
     * @description Schema representing a record in the 'summary' table.
     * Contains precomputed climate and weather statistics across time dimensions.
     */
    SummaryRecord: {
      /**
       * Station Id
       * @description Station identifier (NOT NULL in DB)
       */
      station_id?: string;
      /**
       * Definition Id
       * @description Definition identifier (NOT NULL in DB)
       */
      definition_id?: string;
      /**
       * Time Type
       * @description Time dimension type (e.g. annual, monthly)
       */
      time_type?: string;
      /**
       * Time Value
       * @description Time dimension value (e.g. year '2024')
       */
      time_value?: string;
      /**
       * Summary Type
       * @description Summary calculation type
       */
      summary_type?: string;
      /**
       * Summary Element
       * @description Climate element (e.g. rain, temp)
       */
      summary_element?: string;
      /**
       * Summary Name
       * @description Name of specific summary metric
       */
      summary_name?: string;
      /**
       * Summary Value
       * @description Calculated summary metric value
       */
      summary_value?: string;
      /**
       * Time Stamp
       * Format: date-time
       * @description Timestamp of calculation (NOT NULL in DB)
       */
      time_stamp?: string;
      /**
       * Status
       * @description Processing status (NOT NULL in DB)
       */
      status?: string;
    };
    /**
     * SummaryStationMetadataRecord
     * @description Schema representing a record in the 'summary_station_metadata' table.
     * Indexes which summary types and definitions are available for a given station.
     */
    SummaryStationMetadataRecord: {
      /**
       * Station Id
       * @description Station identifier (NOT NULL in DB)
       */
      station_id?: string;
      /**
       * Summary Type
       * @description Summary type available for this station
       */
      summary_type?: string;
      /**
       * Definition Id
       * @description Definition identifier
       */
      definition_id?: string;
      /**
       * Time Stamp
       * Format: date-time
       * @description Record timestamp (NOT NULL in DB)
       */
      time_stamp?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  /**
   * Get Status
   * @description Health check endpoint for v2.
   */
  get_status_v2_status__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': string;
        };
      };
    };
  };
  /**
   * Get Annual Rainfall Summaries
   * @description Retrieve annual rainfall summaries from PostgreSQL.
   */
  get_annual_rainfall_summaries_v2_annual_rainfall_summaries__post: {
    requestBody: {
      content: {
        'application/json': components['schemas']['AnnualRainfallSummariesParameters'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['AnnualRainfallSummariesResponce'];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  /**
   * Get Annual Temperature Summaries
   * @description Retrieve annual temperature summaries from PostgreSQL.
   */
  get_annual_temperature_summaries_v2_annual_temperature_summaries__post: {
    requestBody: {
      content: {
        'application/json': components['schemas']['AnnualTemperatureSummariesParameters'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['AnnualTemperatureSummariesResponce'];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  /**
   * Get Crop Success Probabilities
   * @description Retrieve full crop success probabilities lookup table from PostgreSQL.
   */
  get_crop_success_probabilities_v2_crop_success_probabilities__post: {
    requestBody: {
      content: {
        'application/json': components['schemas']['CropSuccessProbabilitiesParameters'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['CropSuccessProbabilitiesResponce'];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  /**
   * Get Monthly Temperature Summaries
   * @description Retrieve monthly temperature summaries from PostgreSQL.
   */
  get_monthly_temperature_summaries_v2_monthly_temperature_summaries__post: {
    requestBody: {
      content: {
        'application/json': components['schemas']['MonthlyTemperatureSummariesParameters'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['MonthlyTemperatureSummariesResponce'];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  /**
   * Get Season Start Probabilities
   * @description Retrieve cumulative season start probabilities from PostgreSQL.
   */
  get_season_start_probabilities_v2_season_start_probabilities__post: {
    requestBody: {
      content: {
        'application/json': components['schemas']['SeasonStartProbabilitiesParameters'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['SeasonStartProbabilitiesResponce'];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  /**
   * Read Stations
   * @description Retrieve all stations for a given country code.
   */
  read_stations_v2_station__country__get: {
    parameters: {
      path: {
        country:
          | 'zm'
          | 'mw'
          | 'zw'
          | 'zm_test'
          | 'mw_test'
          | 'zw_test'
          | 'zm_workshops'
          | 'mw_workshops'
          | 'zw_workshops'
          | 'internal_tests';
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['StationListResponce'];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  /**
   * Read Station Detail
   * @description Retrieve station metadata and climate definitions for a station.
   */
  read_station_detail_v2_station__country___station_id__get: {
    parameters: {
      path: {
        country:
          | 'zm'
          | 'mw'
          | 'zw'
          | 'zm_test'
          | 'mw_test'
          | 'zw_test'
          | 'zm_workshops'
          | 'mw_workshops'
          | 'zw_workshops'
          | 'internal_tests';
        station_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['StationAndDefintionResponce'];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  /** Run Select Query */
  run_select_query_v2_select_query__post: {
    requestBody: {
      content: {
        'application/json': components['schemas']['SelectQueryRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['SelectQueryResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  /** Get Documents */
  get_documents_v2_documents__country__get: {
    parameters: {
      query?: {
        prefix?: string;
        max_results?: number;
        match_glob?: string;
      };
      path: {
        country:
          | 'zm'
          | 'mw'
          | 'zw'
          | 'zm_test'
          | 'mw_test'
          | 'zw_test'
          | 'zm_workshops'
          | 'mw_workshops'
          | 'zw_workshops'
          | 'internal_tests';
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['DocumentMetadata'][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  /**
   * Download Document
   * @description Download a specific document
   */
  download_document_v2_documents__country___filepath__get: {
    parameters: {
      path: {
        country:
          | 'zm'
          | 'mw'
          | 'zw'
          | 'zm_test'
          | 'mw_test'
          | 'zw_test'
          | 'zm_workshops'
          | 'mw_workshops'
          | 'zw_workshops'
          | 'internal_tests';
        filepath: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['DocumentMetadata'][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
}
