import { execSync } from 'child_process';
import * as crypto from 'crypto';
import * as fs from 'fs';
import * as path from 'path';
import type {
  IClimateAuditReport,
  IIncomingClimateRecord,
  IMonthlyStationData,
  IStationCapabilities,
  IStationData,
} from '@picsa/models';
import {
  auditMonthlyChanges,
  calculateStationCapabilities,
  formatMonthlyCsv,
  generateMarkdownAuditReport,
  parseAnnualCsv,
  parseMonthlyCsv,
  pivotLongToWideMonthly,
} from '@picsa/utils';

const ROOT_DIR = path.resolve(__dirname, '../../../../');
const CLIMATE_TOOL_ASSETS = path.join(ROOT_DIR, 'apps/picsa-tools/climate-tool/src/assets/summaries');
const DEFAULT_FIXTURE_PATH = path.join(__dirname, 'fixtures/sample-long-data.json');
const DEFAULT_REPORT_PATH = path.join(ROOT_DIR, 'dist/climate-sync-report.md');
const SUPPORTED_COUNTRIES = ['mw', 'zm', 'zw'];

export interface CliArgs {
  country?: string;
  station?: string;
  input?: string;
  auditOnly?: boolean;
  computeExisting?: boolean;
  report?: string;
}

export function parseCliArgs(): CliArgs {
  const args = process.argv.slice(2);
  const result: CliArgs = {};

  for (const arg of args) {
    if (arg === '--audit-only') {
      result.auditOnly = true;
    } else if (arg === '--compute-existing') {
      result.computeExisting = true;
    } else if (arg.startsWith('--country=')) {
      result.country = arg.replace('--country=', '').toLowerCase();
    } else if (arg.startsWith('--station=')) {
      result.station = arg.replace('--station=', '').toLowerCase();
    } else if (arg.startsWith('--input=')) {
      result.input = path.resolve(process.cwd(), arg.replace('--input=', ''));
    } else if (arg.startsWith('--report=')) {
      result.report = path.resolve(process.cwd(), arg.replace('--report=', ''));
    }
  }

  return result;
}

export function getCountryCapsPath(country: string): string {
  return path.join(
    ROOT_DIR,
    `apps/picsa-tools/climate-tool/src/app/data/stations/${country.toLowerCase()}/capabilities.generated.ts`,
  );
}

export function loadCountryCapabilities(country: string): Record<string, IStationCapabilities> {
  const capsPath = getCountryCapsPath(country);
  if (!fs.existsSync(capsPath)) {
    return {};
  }
  // 1. Try loading via require (works natively when executed via tsx)
  try {
    delete require.cache[require.resolve(capsPath)];
    const mod = require(capsPath);
    const key = `${country.toUpperCase()}_STATION_CAPABILITIES`;
    if (mod[key]) {
      return mod[key];
    }
  } catch {
    // Fall back to safe static string parsing if require fails
  }
  // 2. Safe static JSON extraction (handles unquoted keys, single quotes, trailing commas without eval)
  try {
    const content = fs.readFileSync(capsPath, 'utf-8');
    const match = content.match(/=\s*(\{[\s\S]*?\});?\s*$/);
    if (match) {
      const jsonText = match[1]
        .replace(/'/g, '"')
        .replace(/([{,]\s*)([a-zA-Z0-9_]+)\s*:/g, '$1"$2":')
        .replace(/,\s*([}\]])/g, '$1');
      return JSON.parse(jsonText);
    }
  } catch {
    return {};
  }
  return {};
}

export function writeCountryCapabilities(country: string, caps: Record<string, IStationCapabilities>): void {
  const capsPath = getCountryCapsPath(country);
  const countryUpper = country.toUpperCase();
  const dir = path.dirname(capsPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  // Sort station keys alphabetically for deterministic output
  const sortedCaps: Record<string, IStationCapabilities> = {};
  for (const key of Object.keys(caps).sort((a, b) => a.localeCompare(b))) {
    sortedCaps[key] = caps[key];
  }

  const content = `import type { IStationCapabilities } from '@picsa/models';

/**
 * Automatically generated station capabilities and data availability descriptors for ${countryUpper}.
 * Generated by apps/picsa-scripts/src/climate/sync-climate-data.ts.
 * Do NOT edit manually.
 */
export const ${countryUpper}_STATION_CAPABILITIES: Record<string, IStationCapabilities> = ${JSON.stringify(
    sortedCaps,
    null,
    2,
  )};
`;
  fs.writeFileSync(capsPath, content, 'utf-8');
  console.log(`  ✅ Updated ${countryUpper} capabilities: ${capsPath} (${Object.keys(sortedCaps).length} stations)`);
}

export function computeSha256(content: string): string {
  return crypto.createHash('sha256').update(content, 'utf8').digest('hex');
}

/**
 * Query Git for the date (YYYY-MM-DD) when a station's data files were last committed.
 * Checks both annual and monthly CSV paths (if present) and returns the latest commit date.
 * Falls back to current date (YYYY-MM-DD) if uncommitted, untracked, or if git command fails.
 */
export function getStationGitLastUpdatedDate(filePaths: string[]): string {
  const existingPaths = filePaths.filter((p) => fs.existsSync(p));
  if (existingPaths.length === 0) {
    return new Date().toISOString().slice(0, 10);
  }
  try {
    const quotedPaths = existingPaths.map((p) => `"${p}"`).join(' ');
    const stdout = execSync(`git log -1 --format="%as" -- ${quotedPaths}`, {
      cwd: ROOT_DIR,
      encoding: 'utf-8',
      stdio: ['pipe', 'pipe', 'ignore'],
    }).trim();
    if (stdout && /^\d{4}-\d{2}-\d{2}$/.test(stdout)) {
      return stdout;
    }
  } catch {
    // Ignore git error and fall back
  }
  return new Date().toISOString().slice(0, 10);
}

/**
 * Retroactively compute capabilities for all existing station CSV files in a country.
 */
export function computeExistingCapabilitiesForCountry(
  country: string,
  options: { auditReport: IClimateAuditReport; auditOnly?: boolean },
): Record<string, IStationCapabilities> {
  const countryDir = path.join(CLIMATE_TOOL_ASSETS, country);
  if (!fs.existsSync(countryDir)) {
    console.warn(`  ⚠️ Assets folder for country '${country}' does not exist: ${countryDir}`);
    return {};
  }

  const existingCaps = loadCountryCapabilities(country);
  const updatedCaps: Record<string, IStationCapabilities> = { ...existingCaps };

  const allFiles = fs.readdirSync(countryDir);
  const annualFiles = allFiles.filter((f) => f.endsWith('.csv') && !f.endsWith('.monthly.csv'));

  console.log(`\nProcessing existing stations for ${country.toUpperCase()} (${annualFiles.length} stations)...`);

  for (const file of annualFiles) {
    const stationId = path.basename(file, '.csv');
    const annualCsvPath = path.join(countryDir, file);
    const monthlyCsvPath = path.join(countryDir, `${stationId}.monthly.csv`);

    const annualCsvContent = fs.readFileSync(annualCsvPath, 'utf-8');
    const annualData = parseAnnualCsv(annualCsvContent);

    let monthlyData: IMonthlyStationData[] = [];
    let monthlyCsvContent = '';
    if (fs.existsSync(monthlyCsvPath)) {
      monthlyCsvContent = fs.readFileSync(monthlyCsvPath, 'utf-8');
      monthlyData = parseMonthlyCsv(monthlyCsvContent);
    }

    // Base summary metadata (contentHash, lastUpdated, years, totalMissingYears) on annual data
    const contentHash = computeSha256(annualCsvContent.trim());

    const prevCap = existingCaps[stationId];
    const isUnchanged = prevCap?.contentHash === contentHash;
    const stationLastUpdated =
      isUnchanged && prevCap?.lastUpdated && /^\d{4}-\d{2}-\d{2}$/.test(prevCap.lastUpdated)
        ? prevCap.lastUpdated
        : getStationGitLastUpdatedDate([annualCsvPath]);

    const capabilities = calculateStationCapabilities({
      annualData,
      monthlyData,
      contentHash,
      lastUpdated: stationLastUpdated,
    });

    updatedCaps[stationId] = capabilities;

    options.auditReport.stationsSummary.push({
      id: `${country}:${stationId}`,
      status: isUnchanged ? 'UNCHANGED' : prevCap ? 'UPDATED' : 'NEW',
      years: capabilities.years,
      totalMissingYears: capabilities.totalMissingYears,
      annual: capabilities.annual,
      monthly: capabilities.monthly,
      hasRainfall: (capabilities.annual?.includes('rainfall') || capabilities.monthly?.includes('rainfall')) ?? false,
      hasTemperature:
        (capabilities.annual?.includes('temp_min') ||
          capabilities.annual?.includes('temp_max') ||
          capabilities.monthly?.includes('temp_min') ||
          capabilities.monthly?.includes('temp_max')) ??
        false,
      hash: contentHash,
    });
    options.auditReport.totalStationsProcessed++;
  }

  if (!options.auditOnly) {
    writeCountryCapabilities(country, updatedCaps);
  }

  return updatedCaps;
}

export async function runSync(options: CliArgs = {}): Promise<IClimateAuditReport> {
  const today = new Date().toISOString().slice(0, 10);
  const auditReport: IClimateAuditReport = {
    timestamp: today,
    totalStationsProcessed: 0,
    stationsSummary: [],
    historicalRevisions: [],
    missingnessRegressions: [],
    sanityViolations: [],
  };

  const reportPath = options.report || DEFAULT_REPORT_PATH;

  // 1. Retroactive capabilities computation for existing data
  if (options.computeExisting || (!options.input && !options.station)) {
    const countriesToProcess = options.country && options.country !== 'all' ? [options.country] : SUPPORTED_COUNTRIES;

    for (const c of countriesToProcess) {
      computeExistingCapabilitiesForCountry(c, {
        auditReport,
        auditOnly: options.auditOnly,
      });
    }

    // Write audit report
    const reportMd = generateMarkdownAuditReport(auditReport);
    const reportDir = path.dirname(reportPath);
    if (!fs.existsSync(reportDir)) {
      fs.mkdirSync(reportDir, { recursive: true });
    }
    fs.writeFileSync(reportPath, reportMd, 'utf-8');
    console.log(`\n  📄 Audit report written: ${reportPath}`);

    console.log(`\n======================================================`);
    console.log(`[Retroactive Capabilities Computation Complete]`);
    console.log(`  Total Stations Processed: ${auditReport.totalStationsProcessed}`);
    console.log(`======================================================\n`);

    return auditReport;
  }

  // 2. Incoming data synchronization
  const country = (options.country || 'zm').toLowerCase();
  const inputPath = options.input || DEFAULT_FIXTURE_PATH;

  console.log(`\nStarting Climate Data Sync for Country: ${country.toUpperCase()}`);
  console.log(`  Input: ${inputPath}`);
  console.log(`  Mode: ${options.auditOnly ? 'AUDIT ONLY' : 'SYNC & WRITE'}`);

  if (!fs.existsSync(inputPath)) {
    throw new Error(`Input file does not exist: ${inputPath}`);
  }

  const rawJson = fs.readFileSync(inputPath, 'utf-8');
  const incomingRecords: IIncomingClimateRecord[] = JSON.parse(rawJson);
  console.log(`  Loaded ${incomingRecords.length} incoming long records.`);

  // Group records by station_id
  const stationGroups = new Map<string, IIncomingClimateRecord[]>();
  for (const record of incomingRecords) {
    if (options.station && record.station_id.toLowerCase() !== options.station) {
      continue;
    }
    const list = stationGroups.get(record.station_id) || [];
    list.push(record);
    stationGroups.set(record.station_id, list);
  }

  console.log(`  Identified ${stationGroups.size} station(s) to process.`);
  auditReport.totalStationsProcessed = stationGroups.size;

  const countryDir = path.join(CLIMATE_TOOL_ASSETS, country);
  const existingCaps = loadCountryCapabilities(country);
  const updatedCaps: Record<string, IStationCapabilities> = { ...existingCaps };

  for (const [stationId, records] of stationGroups.entries()) {
    const newMonthlyData = pivotLongToWideMonthly(records, {
      onDuplicate: (dup) => {
        if (dup.isConflict) {
          auditReport.sanityViolations.push({
            stationId,
            month: dup.month,
            rule: 'DUPLICATE_OBSERVATION_CONFLICT',
            message: `Conflicting duplicate observation for '${dup.element}' in month ${dup.month}: earlier value was ${dup.existingValue}, incoming value is ${dup.incomingValue} (overwritten with incoming)`,
            values: {
              element: dup.element,
              earlierValue: dup.existingValue,
              incomingValue: dup.incomingValue,
            },
          });
        }
      },
    });

    const monthlyCsvPath = path.join(countryDir, `${stationId}.monthly.csv`);
    const annualCsvPath = path.join(countryDir, `${stationId}.csv`);

    let previousMonthlyData: IMonthlyStationData[] = [];
    let previousMonthlyCsvContent = '';
    if (fs.existsSync(monthlyCsvPath)) {
      previousMonthlyCsvContent = fs.readFileSync(monthlyCsvPath, 'utf-8');
      previousMonthlyData = parseMonthlyCsv(previousMonthlyCsvContent);
    }

    let annualData: IStationData[] = [];
    let annualCsvContent = '';
    if (fs.existsSync(annualCsvPath)) {
      annualCsvContent = fs.readFileSync(annualCsvPath, 'utf-8');
      annualData = parseAnnualCsv(annualCsvContent);
    }

    // Audit diffing
    const diff = auditMonthlyChanges({
      stationId,
      existingData: previousMonthlyData,
      incomingData: newMonthlyData,
    });

    auditReport.historicalRevisions.push(...diff.revisions);
    auditReport.missingnessRegressions.push(...diff.regressions);
    auditReport.sanityViolations.push(...diff.sanityViolations);

    // Format wide monthly CSV
    const newMonthlyCsvContent = formatMonthlyCsv(newMonthlyData);

    // Deterministic hash of annual + monthly data
    const combinedDataForHash = annualCsvContent
      ? `${annualCsvContent.trim()}\n---\n${newMonthlyCsvContent.trim()}`
      : newMonthlyCsvContent.trim();
    const contentHash = computeSha256(combinedDataForHash);

    // Check if station data is completely unchanged
    const prevCap = existingCaps[stationId];
    const isUnchanged =
      prevCap?.contentHash === contentHash && previousMonthlyCsvContent.trim() === newMonthlyCsvContent.trim();
    const stationLastUpdated =
      isUnchanged && prevCap?.lastUpdated && /^\d{4}-\d{2}-\d{2}$/.test(prevCap.lastUpdated)
        ? prevCap.lastUpdated
        : today;

    // Calculate station capabilities
    const capabilities = calculateStationCapabilities({
      annualData,
      monthlyData: newMonthlyData,
      contentHash,
      lastUpdated: stationLastUpdated,
    });

    updatedCaps[stationId] = capabilities;

    // Station status
    let status: 'NEW' | 'UPDATED' | 'UNCHANGED' = 'NEW';
    if (previousMonthlyCsvContent) {
      status = isUnchanged ? 'UNCHANGED' : 'UPDATED';
    }

    auditReport.stationsSummary.push({
      id: stationId,
      status,
      years: capabilities.years,
      totalMissingYears: capabilities.totalMissingYears,
      annual: capabilities.annual,
      monthly: capabilities.monthly,
      hasRainfall: (capabilities.annual?.includes('rainfall') || capabilities.monthly?.includes('rainfall')) ?? false,
      hasTemperature:
        (capabilities.annual?.includes('temp_min') ||
          capabilities.annual?.includes('temp_max') ||
          capabilities.monthly?.includes('temp_min') ||
          capabilities.monthly?.includes('temp_max')) ??
        false,
      hash: contentHash,
    });

    // Write monthly file if not audit-only
    if (!options.auditOnly) {
      if (!fs.existsSync(countryDir)) {
        fs.mkdirSync(countryDir, { recursive: true });
      }
      fs.writeFileSync(monthlyCsvPath, newMonthlyCsvContent, 'utf-8');
      console.log(`  ✅ Wrote: ${monthlyCsvPath} (${newMonthlyData.length} months)`);
    }
  }

  // Update country capabilities.generated.ts if not audit-only
  if (!options.auditOnly) {
    writeCountryCapabilities(country, updatedCaps);
  }

  // Generate markdown audit report
  const reportMd = generateMarkdownAuditReport(auditReport);
  const reportDir = path.dirname(reportPath);
  if (!fs.existsSync(reportDir)) {
    fs.mkdirSync(reportDir, { recursive: true });
  }
  fs.writeFileSync(reportPath, reportMd, 'utf-8');
  console.log(`  📄 Audit report written: ${reportPath}`);

  // Print summary to terminal
  console.log(`\n======================================================`);
  console.log(`[Climate Sync Complete]`);
  console.log(`  Total Stations: ${auditReport.totalStationsProcessed}`);
  console.log(`  Historical Revisions: ${auditReport.historicalRevisions.length}`);
  console.log(`  Missingness Regressions: ${auditReport.missingnessRegressions.length}`);
  console.log(`  Sanity Violations: ${auditReport.sanityViolations.length}`);
  console.log(`======================================================\n`);

  return auditReport;
}

// Run CLI directly if executed
if (require.main === module) {
  const cliArgs = parseCliArgs();
  runSync(cliArgs).catch((err) => {
    console.error(`[Climate Sync Error]:`, err);
    process.exit(1);
  });
}
