import {
  NOTIFICATION_PREFERENCES_COLLECTION,
  NOTIFICATION_PREFERENCES_SCHEMA_V0,
  NOTIFICATIONS_COLLECTION,
  NOTIFICATIONS_SCHEMA_V0,
} from './schema_V0';

export * from './schema_V0';

export const NOTIFICATIONS_SCHEMA = NOTIFICATIONS_SCHEMA_V0;
export const NOTIFICATION_PREFERENCES_SCHEMA = NOTIFICATION_PREFERENCES_SCHEMA_V0;
export const DB_NOTIFICATIONS_COLLECTION = NOTIFICATIONS_COLLECTION;
export const DB_NOTIFICATION_PREFERENCES_COLLECTION = NOTIFICATION_PREFERENCES_COLLECTION;
