/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import { IEventDataUpdated, IEventFormSaved } from './components/enketo-webform/enketo-webform';
export { IEventDataUpdated, IEventFormSaved } from './components/enketo-webform/enketo-webform';
export namespace Components {
  interface EnketoWebform {
    /**
     * HTML form template
     */
    form: string;
    /**
     * XML form model, as processed by an Enketo Transformer
     */
    model: string;
    showButtons: boolean;
  }
}
export interface EnketoWebformCustomEvent<T> extends CustomEvent<T> {
  detail: T;
  target: HTMLEnketoWebformElement;
}
declare global {
  interface HTMLEnketoWebformElement extends Components.EnketoWebform, HTMLStencilElement {}
  var HTMLEnketoWebformElement: {
    prototype: HTMLEnketoWebformElement;
    new (): HTMLEnketoWebformElement;
  };
  interface HTMLElementTagNameMap {
    'enketo-webform': HTMLEnketoWebformElement;
  }
}
declare namespace LocalJSX {
  interface EnketoWebform {
    /**
     * HTML form template
     */
    form: string;
    /**
     * XML form model, as processed by an Enketo Transformer
     */
    model: string;
    onDataUpdated?: (event: EnketoWebformCustomEvent<IEventDataUpdated>) => void;
    onFormSaved?: (event: EnketoWebformCustomEvent<IEventFormSaved>) => void;
    showButtons?: boolean;
  }
  interface IntrinsicElements {
    'enketo-webform': EnketoWebform;
  }
}
export { LocalJSX as JSX };
declare module '@stencil/core' {
  export namespace JSX {
    interface IntrinsicElements {
      'enketo-webform': LocalJSX.EnketoWebform & JSXBase.HTMLAttributes<HTMLEnketoWebformElement>;
    }
  }
}
