/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface EnketoWebform {
        /**
          * HTML form template
         */
        "form": string;
        /**
          * XML form model, as processed by an Enketo Transformer
         */
        "model": string;
    }
}
declare global {
    interface HTMLEnketoWebformElement extends Components.EnketoWebform, HTMLStencilElement {
    }
    var HTMLEnketoWebformElement: {
        prototype: HTMLEnketoWebformElement;
        new (): HTMLEnketoWebformElement;
    };
    interface HTMLElementTagNameMap {
        "enketo-webform": HTMLEnketoWebformElement;
    }
}
declare namespace LocalJSX {
    interface EnketoWebform {
        /**
          * HTML form template
         */
        "form": string;
        /**
          * XML form model, as processed by an Enketo Transformer
         */
        "model": string;
    }
    interface IntrinsicElements {
        "enketo-webform": EnketoWebform;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "enketo-webform": LocalJSX.EnketoWebform & JSXBase.HTMLAttributes<HTMLEnketoWebformElement>;
        }
    }
}
