# Overrides applied in test environment
version: '3.1'
services:
  db:
    container_name: picsa_db_test
    volumes:
      # remove persistent data volume for test
      - ./config/db:/docker-entrypoint-initdb.d/
    env_file:
      - ../.env.sample

  db_admin:
    container_name: picsa_db_admin_test
    volumes:
      - db_admin_data_test:/var/lib/pgadmin
    env_file:
      - ../.env.sample

  server:
    container_name: picsa_server_test
    env_file:
      - ../.env.sample

  server_dashboard:
    container_name: picsa_server_dashboard_test
    env_file:
      - ../.env.sample

volumes:
  db_admin_data_test:
