# Overrides applied in test environment
version: '3.1'
services:
  db:
    container_name: picsa_db_test
    volumes:
      - ./config/db:/docker-entrypoint-initdb.d/
        # removed db_data volume (do not persist)
    env_file:
      - ../.env.sample

  db_admin:
    container_name: picsa_db_admin_test
    volumes:
      - db_admin_data_test:/var/lib/pgadmin
    env_file:
      - ../.env.sample

  server:
    container_name: picsa_server_test
    volumes:
      - ./cloud-functions:/parse-server/cloud
      # removed server_files volume (do not persist)
    env_file:
      - ../.env.sample

  server_dashboard:
    container_name: picsa_server_dashboard_test
    env_file:
      - ../.env.sample

volumes:
  db_admin_data_test:
