# Ensure build and tests pass

name: Build Test
on:
  pull_request:
    branches:
      - main

# Only keep one active build per ref (e.g. pr branch, push branch, triggering workflow ref)
concurrency:
  group: app-build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'yarn'

      - name: Install node modules
        run: yarn install --immutable

      - run: yarn lint
      # - run: yarn nx test
      # Ensure can also build

      - name: Add mock supabase config
        run: |
          jq -n \
            --arg apiUrl "" \
            --arg anonKey "" \
            '{apiUrl: $apiUrl, anonKey: $anonKey}' \
            > libs/environments/src/supabase/supabase.config.json

      - run: yarn nx build
