# Add github issues to projects board on creation

# Required Secrets
# - PROJECTS_ACCESS_TOKEN

name: Add issues project
on:
  issues:
    types:
      - opened
jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@RELEASE_VERSION
        with:
          # You can target a repository in a different organization
          # to the issue
          project-url: https://github.com/orgs/e-picsa/projects/1
          github-token: ${{ secrets.PROJECTS_ACCESS_TOKEN }}
          # labeled: bug, needs-triage
          # label-operator: OR
