# Deploy preview url for labelled PRs

# Required Secrets
# - FIREBASE_SERVICE_ACCOUNT

name: Web Preview
on:
  pull_request:
    types: [labeled, synchronize]
    branches:
      - main
jobs:
  web_preview_resources:
    if: contains(github.event.pull_request.labels.*.name, 'Test - Preview')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - run: yarn install --immutable
      - run: yarn nx run picsa-apps-extension-app:build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: picsa-apps
          target: extension-toolkit
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
