# Deploy preview url for labelled PRs

# Required Secrets
# - FIREBASE_SERVICE_ACCOUNT

name: Web Preview
on:
  pull_request:
    types: [labeled, synchronize]
    branches:
      - main
jobs:
  web_preview:
    if: contains(github.event.pull_request.labels.*.name, 'Test - Preview')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      #############################################################################
      #         Node Modules
      # Manually restore any previous cache to speed install
      # As immutable install will not change cache only save new cache if not hit
      # Uses fine-grained methods from https://github.com/actions/cache
      #############################################################################
      - uses: actions/cache/restore@v3
        id: cache
        with:
          path: ./.yarn/cache
          key: ${{ runner.os }}-node-modules-yarn-v1-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-yarn-v1-
      - name: Install node modules
        run: yarn install --immutable
      - uses: actions/cache/save@v3
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          path: ./.yarn/cache
          key: ${{ runner.os }}-node-modules-yarn-v1-${{ hashFiles('yarn.lock') }}
      - run: yarn nx run picsa-apps-extension-app:build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: picsa-apps
          target: extension-toolkit
          expires: 30d
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
