# Deploy preview url for labelled PRs

# Required Secrets
# - FIREBASE_SERVICE_ACCOUNT

name: Web Preview
on:
  pull_request:
    types: [labeled, synchronize]
    branches:
      - main
jobs:
  web_preview_resources:
    if: contains(github.event.pull_request.labels.*.name, 'Test - Preview')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ./.yarn/cache
          # If cachebusting required (e.g. breaking yarn changes on update) change `v1` to another number
          key: ${{ runner.os }}-node-modules-yarn-v20221105-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-v20221105-
      - run: yarn install
      - run: yarn nx run picsa-apps-extension-app:build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: picsa-apps
          target: extension-toolkit
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
